# -*- coding: utf-8 -*-
"""TUBES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MPOtKG9EDilAkh2UUQ39y2EQ-TYICKT
"""

# Menghitung derajat keanggotaan (membership degree)
def triangle(x, a, b, c):
    if x <= a or x >= c:
        return 0.0
    elif x <= b:
        return (x - a) / (b - a)
    else:
        return (c - x) / (c - b)

# Fuzzifikasi hutan
def fuzzy_hutan(x):
    R = triangle(x, 0, 0, 2500)
    S = triangle(x, 1500, 4000, 6000)
    T = triangle(x, 5000, 8000, 8000)
    return {"Sempit": R, "Sedang": S, "Luas": T}

# Fuzzifikasi Non-hutan
def fuzzy_non_hutan(x):
    R = triangle(x, 0, 0, 3000)
    S = triangle(x, 2000, 5000, 7000)
    T = triangle(x, 6000, 9000, 9000)
    return {"Rendah": R, "Sedang": S, "Tinggi": T}

# Memetakan nilai output numerik y ke membership degree
def output_mem(y, label):
    if label == "R":
        return triangle(y, 0, 0, 50)
    elif label == "S":
        return triangle(y, 30, 50, 70)
    elif label == "T":
        return triangle(y, 50, 100, 100)
    return 0.0

# Mengelola input numerik (hutan, non_hutan) melalui sistem inferensi fuzzy
def fuzzy_infer_defuzz(hutan, non_hutan):
    fh = fuzzy_hutan(hutan)
    fnh = fuzzy_non_hutan(non_hutan)

    # Aktivasi aturan
    rules = [
        ("R", fh["Sempit"]),  # Hutan R → Skor R
        ("S", min(fh["Sedang"], fnh["Rendah"])),  # Hutan S, NH R → S
        ("S", min(fh["Sedang"], fnh["Sedang"])),  # Hutan S, NH S → S
        ("R", min(fh["Sedang"], fnh["Tinggi"])),  # Hutan S, NH T → R
        ("T", min(fh["Luas"], fnh["Rendah"])),    # Hutan T, NH R → T (ideal)
        ("S", min(fh["Luas"], fnh["Sedang"])),    # Hutan T, NH S → S
        ("R", min(fh["Luas"], fnh["Tinggi"])),    # Hutan T, NH T → R (banyak lahan terbuka)
    ]

    # Agregasi: ambil maksimum per label
    agg = {"R": 0.0, "S": 0.0, "T": 0.0}
    for label, strength in rules:
        if strength > agg[label]:
            agg[label] = strength

    # Defuzzifikasi: centroid di y ∈ [0, 100]
    num = 0.0
    den = 0.0
    y = 0
    while y <= 100:
        mem_val = max(
            agg["R"] * output_mem(y, "R"),
            agg["S"] * output_mem(y, "S"),
            agg["T"] * output_mem(y, "T")
        )
        num += y * mem_val
        den += mem_val
        y += 1.0  # step 1.0

    if den == 0.0:
        return 0.0
    return num / den

# Membaca dan memproses data dari file CSV
# Kemudian mengekstrak informasi (Nama provinsi, persentase hutan, persentase non_hutan)

def read_data(filename):
    data = []
    f = open(filename, 'r', encoding='utf-8')
    lines = f.readlines()
    f.close()

    parsing = False
    for line in lines:
        line = line.strip()
        if line == "":
            continue
        if line.startswith('"1"'):
            parsing = True
        if not parsing:
            continue
        if line.startswith('"INDONESIA"'):
            break

        # Hapus petik luar dan split berdasarkan '","'
        clean_line = line[1:-1] if line.startswith('"') and line.endswith('"') else line
        parts = clean_line.split('","')
        if len(parts) < 5:
            continue
        try:
            provinsi = parts[1].strip('"').strip()
            hutan = float(parts[2])
            non_hutan = float(parts[4])
            data.append([provinsi, hutan, non_hutan])
        except:
            continue
    return data

# Proses Utama & Simpan Output

def main():
    filename = "/content/Rekapitulasi-Luas-Penutupan-Lahan-Hutan-dan-Non-Hutan-Menurut-Provinsi-Tahun-2023-_Ribu-Ha_.csv"

    # Baca data
    data = read_data(filename)

    # Filter dan hitung skor hanya untuk provinsi dengan hutan > non_hutan
    scored = []
    for row in data:
        prov, h, nh = row
        if h > nh:  # hanya pertimbangkan jika hutan lebih luas dari non-hutan
            skor = fuzzy_infer_defuzz(h, nh)
            scored.append([prov, h, nh, skor])

    if not scored:
        print("Tidak ada provinsi dengan luas hutan lebih besar dari non-hutan.")
        return

    # Urutkan berdasarkan skor ekologis tertinggi (descending)
    n = len(scored)
    for i in range(n):
        for j in range(0, n - i - 1):
            if scored[j][3] < scored[j + 1][3]:  # bandingkan skor (index 3)
                scored[j], scored[j + 1] = scored[j + 1], scored[j]

    # Ambil 5 teratas (atau kurang jika tidak cukup)
    top_5 = scored[:5]

    # Simpan ke file
    with open("output_fuzzy_top5_hutan_dominan.txt", "w", encoding="utf-8") as f:
        f.write("=== 5 PROVINSI DENGAN SKOR EKOLOGIS TERBAIK (HUTAN > NON HUTAN) ===\n")
        f.write("Provinsi,Hutan (Ribu Ha),Non Hutan (Ribu Ha),Skor Ekologis\n")
        for p, h, nh, s in top_5:
            f.write(f"{p},{h},{nh},{s:.2f}\n")

    # Tampilkan di layar
    print("=== 5 PROVINSI DENGAN SKOR EKOLOGIS TERBAIK (HUTAN > NON HUTAN) ===")
    print(f"{'Provinsi':<25} {'Hutan':<10} {'Non Hutan':<12} {'Skor'}")
    for p, h, nh, s in top_5:
        print(f"{p:<25} {h:<10} {nh:<12} {s:.2f}")

# Jalankan program
main()